//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcHomework2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Contacts = new HashSet<Contact>();
            this.客戶銀行資訊 = new HashSet<客戶銀行資訊>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string 統一編號 { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<客戶銀行資訊> 客戶銀行資訊 { get; set; }
    }
}
