//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcHomework2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CustomerDetailSum
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> NumOfBanks { get; set; }
        public Nullable<int> NumOfContacts { get; set; }
    }
}
